import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { ArrowLeft, Plus, Trash2, ShoppingCart } from "lucide-react";
import { useOrderMutations } from "@/hooks/useOrders";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

interface LineItem {
  product_name: string;
  sku: string;
  quantity: number;
  unit_price: number;
}

const CreateOrderPage = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { createOrder } = useOrderMutations();

  const [customerName, setCustomerName] = useState("");
  const [customerEmail, setCustomerEmail] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [paymentStatus, setPaymentStatus] = useState("unpaid");
  const [internalNotes, setInternalNotes] = useState("");
  const [shippingLine1, setShippingLine1] = useState("");
  const [shippingCity, setShippingCity] = useState("");
  const [shippingState, setShippingState] = useState("");
  const [shippingZip, setShippingZip] = useState("");
  const [items, setItems] = useState<LineItem[]>([{ product_name: "", sku: "", quantity: 1, unit_price: 0 }]);

  const addItem = () => setItems([...items, { product_name: "", sku: "", quantity: 1, unit_price: 0 }]);
  const removeItem = (i: number) => setItems(items.filter((_, idx) => idx !== i));
  const updateItem = (i: number, field: keyof LineItem, value: any) => {
    const updated = [...items];
    updated[i] = { ...updated[i], [field]: value };
    setItems(updated);
  };

  const subtotal = items.reduce((s, i) => s + i.quantity * i.unit_price, 0);
  const itemCount = items.reduce((s, i) => s + i.quantity, 0);

  const handleSubmit = () => {
    if (!customerName.trim() || !customerEmail.trim()) return;
    const validItems = items.filter((i) => i.product_name.trim());
    if (validItems.length === 0) return;

    createOrder.mutate(
      {
        customer_name: customerName,
        customer_email: customerEmail,
        customer_phone: customerPhone || null,
        customer_id: null,
        status: "pending" as any,
        payment_status: paymentStatus as any,
        fulfillment_status: "unfulfilled" as any,
        subtotal,
        total: subtotal,
        item_count: itemCount,
        internal_notes: internalNotes || null,
        shipping_address: shippingLine1 ? { line1: shippingLine1, city: shippingCity, state: shippingState, zip: shippingZip } : null,
        order_number: "", // auto-generated by trigger
        items: validItems.map((i) => ({
          product_name: i.product_name,
          sku: i.sku || null,
          quantity: i.quantity,
          unit_price: i.unit_price,
          subtotal: i.quantity * i.unit_price,
        })),
      } as any,
      { onSuccess: () => navigate("/admin/orders") }
    );
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" asChild className="shrink-0">
          <Link to="/admin/orders"><ArrowLeft size={18} /></Link>
        </Button>
        <div>
          <h1 className="text-xl md:text-2xl font-display font-bold text-foreground">Create Order</h1>
          <p className="text-sm text-muted-foreground">Manually create a new order</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Customer Info */}
        <div className="bg-card rounded-xl border border-border p-5 space-y-4">
          <h2 className="font-semibold text-foreground">Customer Information</h2>
          <div className="space-y-3">
            <div className="space-y-1.5">
              <Label className="text-sm">Name *</Label>
              <Input value={customerName} onChange={(e) => setCustomerName(e.target.value)} placeholder="Customer name" />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm">Email *</Label>
              <Input type="email" value={customerEmail} onChange={(e) => setCustomerEmail(e.target.value)} placeholder="customer@email.com" />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm">Phone</Label>
              <Input value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} placeholder="Optional" />
            </div>
          </div>
        </div>

        {/* Shipping */}
        <div className="bg-card rounded-xl border border-border p-5 space-y-4">
          <h2 className="font-semibold text-foreground">Shipping Address</h2>
          <div className="space-y-3">
            <div className="space-y-1.5">
              <Label className="text-sm">Street</Label>
              <Input value={shippingLine1} onChange={(e) => setShippingLine1(e.target.value)} placeholder="Street address" />
            </div>
            <div className="grid grid-cols-3 gap-2">
              <div className="space-y-1.5">
                <Label className="text-sm">City</Label>
                <Input value={shippingCity} onChange={(e) => setShippingCity(e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label className="text-sm">State</Label>
                <Input value={shippingState} onChange={(e) => setShippingState(e.target.value)} />
              </div>
              <div className="space-y-1.5">
                <Label className="text-sm">ZIP</Label>
                <Input value={shippingZip} onChange={(e) => setShippingZip(e.target.value)} />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Line Items */}
      <div className="bg-card rounded-xl border border-border p-5 space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold text-foreground">Order Items</h2>
          <Button variant="outline" size="sm" onClick={addItem} className="gap-1.5">
            <Plus size={14} /> Add Item
          </Button>
        </div>
        <div className="space-y-3">
          {items.map((item, i) => (
            <div key={i} className="flex items-end gap-3 p-3 rounded-lg bg-muted/30">
              <div className="flex-1 space-y-1.5">
                <Label className="text-xs">Product Name *</Label>
                <Input value={item.product_name} onChange={(e) => updateItem(i, "product_name", e.target.value)} placeholder="Product name" className="text-sm" />
              </div>
              <div className="w-28 space-y-1.5">
                <Label className="text-xs">SKU</Label>
                <Input value={item.sku} onChange={(e) => updateItem(i, "sku", e.target.value)} placeholder="SKU" className="text-sm font-mono" />
              </div>
              <div className="w-20 space-y-1.5">
                <Label className="text-xs">Qty</Label>
                <Input type="number" min="1" value={item.quantity} onChange={(e) => updateItem(i, "quantity", parseInt(e.target.value) || 1)} className="text-sm" />
              </div>
              <div className="w-24 space-y-1.5">
                <Label className="text-xs">Price</Label>
                <Input type="number" step="0.01" min="0" value={item.unit_price} onChange={(e) => updateItem(i, "unit_price", parseFloat(e.target.value) || 0)} className="text-sm" />
              </div>
              <div className="w-24 text-right pb-2">
                <p className="text-sm font-medium">${(item.quantity * item.unit_price).toFixed(2)}</p>
              </div>
              {items.length > 1 && (
                <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground shrink-0" onClick={() => removeItem(i)}>
                  <Trash2 size={14} />
                </Button>
              )}
            </div>
          ))}
        </div>
        <div className="flex justify-between pt-3 border-t border-border">
          <span className="text-sm text-muted-foreground">{itemCount} item{itemCount !== 1 ? "s" : ""}</span>
          <span className="font-semibold text-foreground">Total: ${subtotal.toFixed(2)}</span>
        </div>
      </div>

      {/* Payment & Notes */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-card rounded-xl border border-border p-5 space-y-4">
          <h2 className="font-semibold text-foreground">Payment</h2>
          <div className="space-y-1.5">
            <Label className="text-sm">Payment Status</Label>
            <Select value={paymentStatus} onValueChange={setPaymentStatus}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="unpaid">Unpaid</SelectItem>
                <SelectItem value="paid">Paid</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="bg-card rounded-xl border border-border p-5 space-y-4">
          <h2 className="font-semibold text-foreground">Internal Notes</h2>
          <Textarea value={internalNotes} onChange={(e) => setInternalNotes(e.target.value)} rows={3} placeholder="Notes visible to admins only..." />
        </div>
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3 pt-4">
        <Button variant="outline" asChild><Link to="/admin/orders">Cancel</Link></Button>
        <Button
          onClick={handleSubmit}
          disabled={!customerName.trim() || !customerEmail.trim() || items.every((i) => !i.product_name.trim()) || createOrder.isPending}
          className="gap-1.5"
        >
          <ShoppingCart size={14} /> Create Order
        </Button>
      </div>
    </div>
  );
};

export default CreateOrderPage;
